# --------------------------

language: node_js
os: linux

env:
  global:
    - CHECKSUM="./.checksum"
    - BUILD="./bin/build.sh"
    - BOT="./botapp"
    - WEB="./web"

node_js:
  - "lts/*"

branches:
  only:
    - master

before_install:
  - npm install -g npm@6.8.0
  - chmod ugo+x $BUILD

install:
  - $BUILD -install $BOT $WEB

before_script:
  - npm prune

script:
  - $BUILD -deploy $BOT $WEB

before_cache:
  - rm -rf $BOT/node_modules/.cache"
  - rm -rf $WEB/node_modules/.cache"

cache:
  directories:
    - $CHECKSUM
    - $BOT/node_modules
    - $WEB/node_modules

notifications:
  email:
    on_failure: always

# --------------------------